#!/bin/bash

SENZING_GIT_REPOSITORY=stream-loader

# List possible build ARGs.

BUILD_ARGS=(
    BASE_IMAGE
    SENZING_ACCEPT_EULA
    SENZING_APT_REPOSITORY_URL
    SENZING_DATA_PACKAGE_NAME
    SENZING_DATA_SUBDIRECTORY
)

# Build "BUILD_ARGS_STRING".

BUILD_ARGS_STRING=""
for BUILD_ARG in ${BUILD_ARGS[@]};
do
    if [ ! -z  ${!BUILD_ARG} ]; then
        BUILD_ARGS_STRING="${BUILD_ARGS_STRING}--build-arg ${BUILD_ARG}=${!BUILD_ARG} "
    fi
done

# Print runtime environment.

echo "==========================================================="
echo "== ${SENZING_GIT_REPOSITORY}/hooks/build"
echo "==   Building with file: ${DOCKERFILE_PATH}"
echo "==   Environment variables:"
env | awk -F= '{ print "==     ", $0}'
echo "=="
echo "==   ${BUILD_ARGS_STRING} "
echo "==   Hook version: 1.0.0 - 2022-04-18"
echo "==========================================================="

# Run docker build.

docker build \
    --file ${DOCKERFILE_PATH} \
    --tag ${IMAGE_NAME} \
    ${BUILD_ARGS_STRING} \
    .
